Given a string, return the character with the most value. The value of a character is the difference between the index of its first occurrence and the index of its last occurrence. If there is a tie, return the character that goes first alphabetically.



Example:

Input: 'abcdbcd'

Output: 'b', since difference between first index and last index = 4 - 1 = 3, which ties with the values of c and d but since b goes first alphabetically, that's the most valuable character.

In [2]:
%%time
def answer(s):
    d={}
    for ch in s:
        if ch not in d.keys():
            d[ch] = ch

    for key in d.keys():
        x = s.find(d[key])
        y = s.rfind(d[key])
        if x != -1 and y!= -1:
            d[key] = y-x
    answer = [k for k,v in d.items() if v == max(d.values())]
    answer = sorted(answer)[0]
    return answer

Wall time: 0 ns


In [8]:

s = "abcdbcd"

%timeit answer(s) 

7.02 µs ± 277 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#daily challenge 12

Given a list of 5 floats, return a tuple of the average of the middle 3 floats and the lowest float of that list.



Example:

Input:

[6.4, 11.4, 7.6, 10.5, 8.1]

Returns:

 (9.83, 6.4), 9.83 (rounded off to nearest two decimal places) is the average of 11.4, 7.6 and 10.5 and 6.4 is the lowest float of the list.

In [21]:


def challenge(lst):
    return (round((sum(lst[1:4]))/3,2), min(lst))
    

In [25]:
l = [6.4, 11.4, 7.6, 10.5, 8.1]

challenge(l)

(9.83, 6.4)

Daily Challenge 13
Given a string, create a function that splits the string into pairs of two characters. Put the pairs inside a list then return the list. If a character is missing in a pair, use the character '?' to replace the missing character.



Example:

Input: "abcdefg"

Output = ["ab", "cd", "ef", "g?"]



Input: "abcdef"

Output = ["ab", "cd", "ef"]

In [50]:
s = "abcdefg"
def pair_challenge(s):
    answer = []
    pairs = []
    for ch in s:
        pairs.append(ch)
        if len(pairs) == 2:
            answer.append(pairs)
            pairs =[]
    if len(pairs) == 1:
        pairs.append('?')
        answer.append(pairs)
    result = []
    for pair in answer:
        x = "".join(pair)
        result.append(x)
    return result
    
    

In [49]:
pair_challenge(s)

['ab', 'cd', 'ef']

Given a list of integers, split the list into two, put the arrays on top of each other, then add them together. Return the finished list.

Example:

Input:

[1, 2, 3, 4, 5, 6, 7]

Putting on top:

[1, 2, 3]

[4, 5, 6, 7]

Adding up process:

[1, 2, 3]

+

[4, 5, 6, 7]

------------

[5, 7, 9, 7]

Returns:

[5, 7, 9, 7]

In [115]:
test = [1, 2, 3, 4, 5, 6, 7]

def challenge(lst):
    import numpy as np
    x = len(test)//2
    split_test = np.split(test,[x])
    if len(split_test[0]) != len(split_test[1]):
        split_test[0] = np.append(split_test[0],[0])
    answer = np.add(split_test[0],split_test[1]) 
    return answer
challenge(test)


array([5, 7, 9, 7])

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [64]:
answer = np.add(split_test[0],split_test[1])

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

https://leetcode.com/problems/minimum-time-visiting-all-points/submissions/

In [5]:
def minTimeToVisitAllPoints(points):
    dist_total = []
    for i in range(len(points)-1):
        p1 = [points[i][0],points[i][1]]
        p2 = [points[i+1][0], points[i+1][1]]  
        y = abs(p2[1]-p1[1])
        x = abs(p2[0]-p1[0])
        dist = max(x,y)
        dist_total.append(dist)
    return sum(dist_total)

points = [[1,1],[3,4],[-1,0]]
minTimeToVisitAllPoints(points)

7

Daily Challange #15

[1, 2, 3, 4, 5]

['a', 'b', 'c', 'd', 'e']

In [4]:
# x = [1, 2, 3, 4, 5]
# y = ['a', 'b', 'c', 'd', 'e']

# x= [1, 2, 3]

# y =['a', 'b', 'c', 'd', 'e']

x = [1, 2, 3, 4, 5]
y = ['a', 'b']

In [5]:
z = zip(x,y)

In [6]:
new_list = []
for pair in list(z):
    new_list.append(pair[0])
    new_list.append(pair[1])
print(new_list)

[1, 'a', 2, 'b']


In [7]:
max_range = max(len(x),len(y))

In [8]:
def challenge15(lst1,lst2):
    test_list = []
    for i in range(max(len(lst1),len(lst2))):
        try:
            test_list.append(lst1[i])
        except:
            pass
        try:
            test_list.append(lst2[i])
        except:
            pass
    return test_list

In [9]:
print(challenge15(x,y))

[1, 'a', 2, 'b', 3, 4, 5]


Challenge 16

Given an integer n, find all the integers that is the multiple of 3 from 0 to n. Return the sum of all these integers.



Example:

Input: 

10

Multiples of 3 from 0 to 10:

3, 6, 9

Return sum of these integers:

18

In [68]:
def challenge16(n):
    n = int(n)
    lst = []
    for i in range(0,n+1):
        if i%3==0 and i>0:
            lst.append(i)
    return sum(lst)


In [69]:
challenge16(10)

18

In [70]:
import numpy as np


In [72]:
bats = np.arange(10).reshape(2,5)

In [105]:
A = np.array([[10,15,17],[2, 5, 7],[11,3, 8]])

In [106]:
A[:,1]

array([15,  5,  3])

In [81]:
Big_Data = ["Velocity", "Volume", "Variety" ]

social_data = Big_Data.pop()

print(social_data)

Variety


In [109]:
bool( [ "me", "myself", "I"] )

True

In [119]:
surname = "Rasputin"

advisor = surname

del surname

In [120]:
advisor

'Rasputin'

In [121]:
surname

NameError: name 'surname' is not defined

day 17

Given a list of 11 integers, return a string in the form of a Hong Kong phone number in this format: +852 xxxx xxxx

Only the numbers 2, 3, 5, 6, 7, and 9 can be added after the extension 852.



Example 1:

Input:

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1]

Returns:

"+852 9134 6701"

In [222]:
def hk_number(lst):
    import random
    area = "+852 "
    restriction = [2, 3, 5, 6, 7, 9]
    remaining_digit = ""

    if 8 in lst and 5 in lst and 2 in lst:
        lst.remove(8)
        lst.remove(5)
        lst.remove(2)

        res = False
        while res == False:
            first_digit = lst[random.randint(0,len(lst)-1)]
            if first_digit in restriction:
                res = True
                lst.remove(first_digit)
                first_digit = str(first_digit)

        number = area +first_digit
        while len(lst) > 4:
            remaining_digit = random.choice(lst)
            lst.remove(remaining_digit)
            remaining_digit = str(remaining_digit)
            number += remaining_digit
        number += " "
        while len(lst) > 0:
            remaining_digit = lst[random.randint(0,len(lst)-1)]
            lst.remove(remaining_digit)
            remaining_digit = str(remaining_digit)
            number += remaining_digit
        return number
    else:
        return "No 852 Found"

In [223]:
hk_number([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

'+852 7361 4910'

Daily Challenge 18
Given an integer greater than 0, return a list of all possible palindromes of the integer.



Example:

Input: 

34322122

Output:

[22, 212, 343, 22122]

In [22]:
num = 34322122

def challenge18(num):
    string = str(num)
    answer = []
    for i in range(len(string)-1):
        test = []
        test.append(string[i])
        for j in range(i+1,len(string)):
            test.append(string[j])
            if test == test[::-1]:
                result = "".join(test)
                answer.append(int(result))
    return answer

In [23]:
challenge18(num)

[343, 22, 22122, 212, 22]

Daily 19

Given a string of names with a certain pattern, return a formatted string with a certain pattern. 



Example:

Input:

"Alfred:Black;Carey:Drake;Elena:Ferguson;Georgina:Harrison"

Output:

"(BLACK, ALFRED)(DRAKE, CAREY)(FERGUSON, ELENA)(HARRISON, GEORGINA)"

In [17]:
s = "Alfred:Black;Carey:Drake;Elena:Ferguson;Georgina:Harrison"
def challenge19(s):
    s = s.upper().split(";")
    ans = []
    for pair in s:
        pair = pair.split(":")
        pair = ("("+pair[1]+", "+pair[0]+")")
        ans.append(pair)
    ans = "".join(ans)
    return ans

In [18]:
challenge19(s)

'(BLACK, ALFRED)(DRAKE, CAREY)(FERGUSON, ELENA)(HARRISON, GEORGINA)'

Given a string, count all the lowercase letters. Return a dictionary with the keys as the lowercase letters and the values as the letters' counts respectively. The keys should be sorted in alphabetical order.



Example:

Input:

"apple"

Output:

{'a': 1, 'e': 1, 'l': 1, 'p': 2}

In [28]:


def challenge20(s):
    from collections import Counter
    return {k: v for k, v in sorted(dict(Counter(s)).items(), key=lambda item: item[0])}

In [32]:
def dict_counter(string):

    return {letter: string.count(letter) for letter in sorted(set(string))}

In [33]:
%timeit dict_counter(s)

2.1 µs ± 95.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [34]:
%timeit challenge20(s)

5.06 µs ± 148 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Daily Challenge 21: 

Given a list of mixed integers of different representations, add up the non-string integers and subtract this from the total of string integers.



Example:

Input:

[1, '2', 3, '4', 5]

Output:

-3, because:

total of non-string integers = 1+3+5 = 9

total of string integers = 2+4 = 6

total of string integers - total of non-string integers = -3 

In [9]:
lst = [1, '2', 3, '4', 5]
def challenge21(lst):
    string_lst = []
    int_lst = []
    for i in lst:
        if isinstance(i,str):
            string_lst.append(i)
            string_lst.append("+")
        else:
            int_lst.append(i)
    string_lst.append("0")
    string_lst = eval("".join(string_lst))
    int_lst = sum(int_lst)
    return string_lst - int_lst

%timeit challenge21(lst)

14.2 µs ± 2.5 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
def challenge21_revised(lst):
    return sum([int(i) for i in lst if type(i) == str ]) - sum([i for i in lst if type(i) == int])

In [6]:
%timeit challenge21_revised(lst)

4.34 µs ± 659 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Daily Challenge 22

Given a string of decimal digits, output an integer of its binary representation like below:



Example:

Input: "2973"

"2" => 10

"9" => 1001

"7" => 111

"3" => 11

Therefore output is 10100111111, because of 10+1001+111+11.

In [6]:
def challenge22(s):
    return "".join([bin(int(num))[2:] for num in s])
challenge22("2973")

'10100111111'

Given an input integer x, return a list of integers in which the sum is equal to x. The integers inside the list must consist of values that are a power of 3. For example:

1 is a possible number of the list because of 3^0 => 1

3 is also a possible number of the list because 3^1 => 3

In [57]:
def challenge23(n):
    import math
    answer = []
    for i in range(math.ceil(math.log(n)/math.log(3)), -1, -1):
        while 3**i < n and (sum(answer)+3**i <= n):
                answer.append(3**i)

        if sum(answer) == n:
            return answer

In [60]:
challenge23(99)

[81, 9, 9]

challenge24

Given a number, return the difference between the maximum and minimum numbers that can be formed when the digits are rearranged.


In [26]:
def challenge24(number):
    return int("".join(sorted(str(number), reverse=True)))-int("".join(sorted(str(number))))

In [30]:
challenge24(112)

99

#Daily Challenge 25

An anagram is a word, x, formed by rearranging the letters that make up another word, y, and using up all the letters in y at the same frequency. For example, "dear" is an anagram of "read" and "plead" is an anagram of "paled".

The Hamming distance between two strings is the number of positions at which they differ. Hamming distances can only be calculated for strings of equal length.

s1 = "eleven"

s2 = "twelve"

They only have the third position (index 2) in common, giving them a Hamming distance of 5.

As anagrams are of identical length, the Hamming distance between them can be calculated.

s1 = "read"

s2 = "dear"

These strings differ at the first and last positions, giving them a Hamming distance of 2. "Plead" and "paled" have a Hamming distance of 3.

Create a function that takes two strings, and returns:

True if they are anagrams of each other and their Hamming distance is equal to their length (i.e. no letters in the same positions).

False if they aren't anagrams, or Their Hamming distance if they are anagrams with >=1 letter at the same index. Examples

max_ham("dear", "read") ➞ 2

max_ham("dare", "read") ➞ True

max_ham("solemn", "molest") ➞ False

In [60]:
s1 = "solemn"
s2 = "molests"


def challenge25(s1,s2):
    if len(s1) != len(s2):
        return "Strings are not equal in length, cannot be anagram"
    anagram = False
    #is anagram?
    if sorted(s1) == sorted(s1):
        anagram = True
    #find hamming distance
    hamming_count = 0
    for i in range(len(s1)):
        if s1[i] == s2[i]:
            hamming_count +=1
    if hamming_count == 0 and anagram == True:
        return True
    elif hamming_count != 0 and anagram == True:
        return hamming_count
    else:
        return False


In [61]:
%timeit challenge25("dear","read")

2.81 µs ± 389 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [52]:
def max_ham(a,b):
    a_sorted = sorted(a)
    b_sorted = sorted(b)
    if a_sorted == b_sorted:
        ham_dist = 0
        for i in range(len(a)):
            if a[i] == b[i]:
                ham_dist += 1
        if ham_dist == 0:
            return True
        else:
            return ham_dist
    else:
        return False

Create a function that takes a list and returns a new list containing only prime numbers.

Examples

filter_primes([7, 9, 3, 9, 10, 11, 27]) ➞ [7, 3, 11]

filter_primes([10007, 1009, 1007, 27, 147, 77, 1001, 70]) ➞ [10007, 1009]

filter_primes([1009, 10, 10, 10, 3, 33, 9, 4, 1, 61, 63, 69, 1087, 1091, 1093, 1097]) ➞ [1009, 3, 61, 1087, 1091, 1093, 1097]

In [78]:
nums = [7, 9, 3, 9, 10, 11, 27]

def challenge26(nums):
    lst = []
    for num in nums:
        prime = True
        for i in range(2,int(num/2+1)):
            if num % i == 0 and num != i:
                prime = False
        if prime == True:
            lst.append(num)
    return lst

In [79]:
challenge26([10007, 1009, 1007, 27, 147, 77, 1001, 70])

[10007, 1009]

Mona has created a method to sort a list in ascending order.

Starting from the left of the list, she compares numbers by pairs. If the first pair is ordered [smaller number, larger number], she moves on. If the first pair is ordered [larger number, smaller number], she swaps the two integers before moving on to the next pair. She repeats this process until she reaches the end of the list.

Then, she moves back to the beginning of the list and repeats this process until the entire list is sorted.

If the unsorted list is: [3, 9, 7, 4], she will perform the following steps (note Swaps here refers to cumulative swaps):

She starts with the first pair. [3, 9] is in order, move on. List: [3, 9, 7, 4]. Swaps: 0. [9, 7] is not. Swap. List: [3, 7, 9, 4]. Swaps: 1 [9, 4] is not. Swap. List: [3, 7, 4, 9]. Swaps: 2 Check if list is sorted. It is not, so start over at first pair. [3, 7] is in order, move on. List: [3, 7, 4, 9]. Swaps: 2 [7, 4] is not. Swap. List: [3, 4, 7, 9]. Swaps: 3. [7, 9] is in order, move on. List: [3, 4, 7, 9]. Swaps: 3. Check if list is sorted. It is. End. Sorting the list [3, 9, 7, 4] takes her 3 swaps. Write a function that takes in an unsorted list and returns the number of swaps it takes for the list to be sorted according to Mona's algorithm.

Examples

number_of_swaps([5, 4, 3]) ➞ 3

number_of_swaps([1, 3, 4, 5]) ➞ 0

number_of_swaps([5, 4, 3, 2]) ➞ 6

In [17]:
nums = [5,4,3]


def number_of_swaps(nums):
    count = 0
    for i in range(0,len(nums)-1):
        for j in range(i+1,len(nums)):
            if nums[j] < nums[i]:
                nums[j],nums[i] = nums[i],nums[j]
                count +=1
    return count

In [26]:
%timeit number_of_swaps([5, 4, 3, 2])

5.49 µs ± 853 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [27]:
def swapswaps(lst):
    count = 0
    while lst != sorted(lst):
        for i in range(len(lst)-1):
            if lst[i] > lst[i+1]:
                count+=1
                lst[i],lst[i+1] = lst[i+1],lst[i]
    return count

In [28]:
%timeit swapswaps([5, 4, 3, 2])

7.34 µs ± 584 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


A string is an almost-palindrome if, by changing only one character, you can make it a palindrome. Create a function that returns True if a string is an almost-palindrome and False otherwise.

Examples

almost_palindrome("abcdcbg") ➞ True

#Transformed to "abcdcba" by changing "g" to "a".

almost_palindrome("abccia") ➞ True

#Transformed to "abccba" by changing "b" to "a".

almost_palindrome("abcdaaa") ➞ False

#Can't be transformed to a palindrome in exactly 1 turn.

almost_palindrome("1234312") ➞ False

In [42]:
string = "abcddbg"
def almost_palindrome(string):
    count = 0
    string_forwards = list(string)
    string_backwards = list(string)[::-1]
    for i in range(len(string_forwards)):
        if string_forwards[i] != string_backwards[i]:
            count+=1
    return True if count == 2 else False

In [56]:
almost_palindrome("rBcecar")

True

In [9]:
a = np.array([[0, 1, 1], [2, 3, 1]])
a

array([[0, 1, 1],
       [2, 3, 1]])

In [10]:
a+=3
a

array([[3, 4, 4],
       [5, 6, 4]])

In [11]:
b= a+4
b

array([[ 7,  8,  8],
       [ 9, 10,  8]])

In [14]:
print([i+j for i in "abc" for j in "def"])

['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']


In [16]:
square = lambda x: x**2

cube = lambda x: x**3

inverse = lambda x: 1/x

funcs = [inverse, square, cube]

list(map( lambda f: f(4) , funcs ))

[0.25, 16, 64]

1732. Find the Highest Altitude

There is a biker going on a road trip. The road trip consists of n + 1 points at different altitudes. The biker starts his trip on point 0 with altitude equal 0.

You are given an integer array gain of length n where gain[i] is the net gain in altitude between points i​​​​​​ and i + 1 for all (0 <= i < n). Return the highest altitude of a point.

Input: gain = [-5,1,5,0,-7]
Output: 1
Explanation: The altitudes are [0,-5,-4,1,1,-6]. The highest is 1.

In [9]:
class Solution:
    def largestAltitude(self, gain: List[int]) -> int:
        max_alt = 0
        alt=0
        alt_l = []
        for step in gain:
            alt += step
            alt_l.append(alt)
        return max(alt_l) if max(alt_l) > 0 else 0

0


In [39]:
arr = [3,0,1,1,9,7]
a = 7
b = 2
c = 3

In [40]:
print(arr[0])

3


In [47]:
count = 0
for i in range(len(arr)-2):
    for j in range(i+1,len(arr)-1):
        for k in range(j+1,len(arr)):
            if (abs(arr[i] - arr[j]) <= a) and (abs(arr[j] - arr[k]) <= b) and (abs(arr[i] - arr[k]) <= c):
                count += 1
count

4

In [50]:
nums = [12,345,2,6,7896]
count = 0
for num in nums:
    if len(str(num)) % 2 == 0:
        count += 1
count

2

In [40]:
# Daily Challenge 29

def challenge29(n,a,b):
    count = 0
    for i in range(int(a**(1/n))-1,int(b**(1/n))+1):
        if i**n >= a and i**n <= b:
            count += 1
    return count

In [41]:
%timeit challenge29(2,49,65)
print(challenge29(3,1,27))
print(challenge29(10,1,5))
print(challenge29(5,31,33))
print(challenge29(4,250,1300))

4.27 µs ± 987 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3
1
1
3


In [42]:
def power_ranger(n, a, b):

    return len([i**(1/n) for i in range(a, b+1) if i**(1/n) % 1 == 0])

In [43]:
%timeit power_ranger(2,49,65)

13.1 µs ± 1.15 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [44]:
def powpow(n,a,b):
    return len([ i**n for i in range(0,int((pow(b,(1/n))))+1) if (a <= i**n <= b) ])

In [48]:
%timeit powpow(4,250,1300)
%timeit challenge29(4,250,1300)
%timeit power_ranger(4,250,1300)

6.03 µs ± 690 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.3 µs ± 539 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
591 µs ± 78.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Given an integer, create a function that returns the next prime. If the number is prime, return the number itself.

Examples

next_prime(12) ➞ 13

next_prime(24) ➞ 29

next_prime(11) ➞ 11

11 is a prime, so we return the number itself.

In [55]:
def next_prime(num):
    for i in range(num, num*2):
        prime = True
        for j in range(2,int(i/2+1)):
            if i % j == 0 and i != j:
                prime = False
        if prime == True:
            return i

In [59]:
print(next_prime(12))
print(next_prime(24))
print(next_prime(11))

13
29
11


In [66]:
%timeit next_prime(12)

6.42 µs ± 944 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [64]:
import math
def next_prime2(n):
    while True: 
        if sum([1 if n%x==0 else 0 for x in range(2, math.ceil(n**0.5)+1)])!=0:
            n+=1
        else:
            return n

In [69]:
next_prime2(11)

11