In [122]:
#Daily Challenge 40
import numpy as np
a = [ [5, 5], [6, 7], [9, 1] ]

In [123]:
def transpose_matrix(a):
    full_lst = [j for i in a for j in i]
    answer = []
    for num in range(len(a[0])):
        tempo_lst = []
        for i in range(num,len(full_lst),len(a[0])):
            tempo_lst.append(full_lst[i])
        answer.append(tempo_lst)
    return answer

Write a function that replaces each integer with the next largest in the list.

Examples

replace_next_largest([5, 7, 3, 2, 8]) ➞ [7, 8, 5, 3, -1]

replace_next_largest([2, 3, 4, 5]) ➞ [3, 4, 5, -1]

replace_next_largest([1, 0, -1, 8, -72]) ➞ [8, 1, 0, -1, -1]

In [177]:
lst = [1, 0, -1, 8, -72]

def replace_next_largest(lst):
    def find_next_biggest(i,lst):
        none = -1
        count = -1
        check_how_many = len(lst)
        while count <= check_how_many:
            count+=1
            i += 1
            if i in lst:
                bigger = i
                return bigger
        return none
    sort = sorted(lst,reverse=True)
    answer = []
    for i in lst:
        i = find_next_biggest(i,lst)
        answer.append(i)
    return answer

In [181]:
print(replace_next_largest([5, 7, 3, 2, 8]))
print(replace_next_largest([2, 3, 4, 5]))
print(replace_next_largest([1, 0, -1, 8, -72]))



[7, 8, 5, 3, -1]
[3, 4, 5, -1]
[8, 1, 0, -1, -1]


freed_prisoners([1, 1, 0, 0, 0, 1, 0]) ➞ 4

freed_prisoners([1, 1, 1]) ➞ 1

freed_prisoners([0, 0, 0]) ➞ 0

freed_prisoners([0, 1, 1, 1]) ➞ 0

In [205]:
lst = [1, 1, 0, 0, 0, 1, 0]

def freed_prisoners(lst):
    count = 0
    for i in range(len(lst)):
        if lst[i] == 1:
            count+=1
            lst = [0 if x==1 else 1 for x in lst]
        else:
            pass
    return count

In [206]:
a = [1, 1, 0, 0, 0, 1, 0]

b = [1, 1, 1]

c = [0, 0, 0]

d = [0, 1, 1, 1]

print(freed_prisoners(a))
print(freed_prisoners(b))
print(freed_prisoners(c))
print(freed_prisoners(d))

4
1
0
1


In [157]:
def semi(n):
    lst = [n]
    while n>1:
        n -= 2
        if n != 0:
            lst.append(n)
    return lst

def alt(n):
    lst = [n]
    positive = True
    while n>1:
        n -= 1
        if n != 0 and positive == True:
            lst_num = n
            lst.append(-lst_num)
            positive = False
        elif n != 0 and positive == False:
            lst_num = n
            lst.append(lst_num)
            positive = True
    return lst

def alt_semi(n):
    import math
    alt_list = alt(n)
    temp_list = []
    for x in alt_list:
        if x > 0:
            y = math.factorial(x)
            temp_list.append(y)
        else:
            y = math.factorial(abs(x))*-1
            temp_list.append(y)
    return sum(temp_list) - math.prod(semi(n))

In [159]:
alt_semi(1)

0

In [160]:
alt_semi(2)

-1

In [161]:
alt_semi(3)

2

In [132]:
import math
def alt_semi2(n):
    semi_sum = 1
    alt_sum = 0
    for i in range(n,1,-2):
        semi_sum*=i
    for j, k in enumerate(range(n,0,-1),0):
        alt_sum += math.factorial(k)*(-1)**(j)
    return alt_sum - semi_sum

In [163]:
%timeit alt_semi2(3)

2.93 µs ± 284 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [164]:
%timeit alt_semi(3)

3.6 µs ± 311 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [43]:
def closest_palindrome(num):
    def check_palindrome(num):
        if str(num)[::-1] == str(num):
            return True
        
    jason = "fat"
    
    if check_palindrome(num) == True:
        return num
    else:
        num_up = num
        num_down = num
        while jason == "fat":
            num_up += 1
            num_down -= 1
            if check_palindrome(num_down) == True:
                return num_down            
            if check_palindrome(num_up) == True:
                return num_up


    

In [65]:
print(closest_palindrome(887))
print(closest_palindrome(100))
print(closest_palindrome(888))
print(closest_palindrome(27))
print(closest_palindrome(1023))

888
99
888
22
1001


In [57]:
def is_pal(num):

    if str(num)[0] == str(num)[-1]:
        return True

def closest_pal(num):

    if is_pal(num) == True:
        return num

    num_list = list(str(num))
    num_list[-1] = num_list[0]
    print(num_list)
    new_num = int(''.join(num_list))
    print(new_num)
    distance = abs(num - new_num)
    print(distance)
    
    if is_pal(num-distance) == True:
        return num - distance
    else:
        return new_num

In [64]:
closest_pal(1023)

['1', '0', '2', '1']
1021
2


1021

In [69]:
d = { "George": 96, "Emily": 95, "Susan": 93, "Jane": 89, "Brett": 82 }
d2 = { "Kate": 92, "Carol": 92, "Jess": 87, "Bruce": 87, "Scott": 84 }

In [143]:
def rank(d,name):
    l = list(d.values())
    rank = [i+1 for i in range(len(l))]
    new_d = {}
    for i in range(len(l)):
#         print(i, l,new_d)
        if i == 0:
            new_d[l[i]] = rank[i]
        elif l[i] == l[i-1]:
            new_d[l[i]] = new_d[l[i-1]]
        else:
            new_d[l[i]] = rank[i]
#         print(new_d)
    for k,v in d.items():
        d[k] = new_d[v]
        print(d)
    return d[name]
    

In [144]:
print(rank({ "George": 96, "Emily": 95, "Susan": 93, "Jane": 89, "Brett": 82 }, "Jane"))
print(rank({ "Kate": 92, "Carol": 92, "Jess": 87, "Bruce": 87, "Scott": 84 },"Bruce"))

{'George': 1, 'Emily': 95, 'Susan': 93, 'Jane': 89, 'Brett': 82}
{'George': 1, 'Emily': 2, 'Susan': 93, 'Jane': 89, 'Brett': 82}
{'George': 1, 'Emily': 2, 'Susan': 3, 'Jane': 89, 'Brett': 82}
{'George': 1, 'Emily': 2, 'Susan': 3, 'Jane': 4, 'Brett': 82}
{'George': 1, 'Emily': 2, 'Susan': 3, 'Jane': 4, 'Brett': 5}
4
{'Kate': 1, 'Carol': 92, 'Jess': 87, 'Bruce': 87, 'Scott': 84}
{'Kate': 1, 'Carol': 1, 'Jess': 87, 'Bruce': 87, 'Scott': 84}
{'Kate': 1, 'Carol': 1, 'Jess': 3, 'Bruce': 87, 'Scott': 84}
{'Kate': 1, 'Carol': 1, 'Jess': 3, 'Bruce': 3, 'Scott': 84}
{'Kate': 1, 'Carol': 1, 'Jess': 3, 'Bruce': 3, 'Scott': 5}
3


92 92
87 87


3

Kate 92
Carol 92
Jess 87
Bruce 87
Scott 84


In [74]:
magic_square_game([2, "100"], [1, "101"])

{'Kate': 1, 'Carol': 1, 'Jess': 3, 'Bruce': 3, 'Scott': 5}

In [80]:
import numpy as np
lst1 = [1, "010"]
lst2 = [3, "101"]
 
    

In [125]:
def magic_square_game(lst1,lst2):
    print("alice")
    alice_array = np.full([3,3],9)
    row = lst1[0]-1
    for i in range(3):
        if i != row:
            pass
        else:
            for j in range(len(lst1[1])):
                alice_array[i][j] = lst1[1][j]
    print(alice_array)

    bob_array = np.full([3,3],9)
    column = lst2[0]-1

    print("bob")
    for c in range(3):
        if c != column:
            pass
        else:
            for r in range(len(lst2[1])):
                bob_array[r,c] = lst2[1][r]
    print(bob_array)

    answer = np.add(bob_array,alice_array)
    print(answer)
    if 0 in answer:
        return True
    elif 2 in answer:
        return True
    else:
        return False

In [126]:
magic_square_game([2, "100"], [1, "101"])

alice
[[9 9 9]
 [1 0 0]
 [9 9 9]]
bob
[[1 9 9]
 [0 9 9]
 [1 9 9]]
[[10 18 18]
 [ 1  9  9]
 [10 18 18]]


False

In [107]:
def magic_square_game2(l1, l2):

    ann_grid = np.full((3,3), 5, dtype=int)
    ann_row = l1[0] - 1
    ann_vals = [i for i in str(l1[1])]
    bob_col = l2[0] - 1
    bob_vals = [i for i in str(l2[1])]
    ann_grid[ann_row] = ann_vals
    #print(ann_grid)
    for i in range(3):
        if ann_grid[:, bob_col][i] == float(bob_vals[i]):
            return True
    return False

In [108]:
%timeit magic_square_game2([2, "100"], [1, "101"])

20.8 µs ± 1.24 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [116]:
def magic_square_game3(alice, bob):
    c = alice[1][bob[0]-1]
    d = bob[1][alice[0]-1]
    if (c == d):
        return True
    else:
        return False

In [118]:
magic_square_game3([2, "001"], [1, "101"])

True

## Day 45
The goal of this challenge is to return Pascal's triangle up to number 29. Pascal's triangle is the sum of the two upper corners.

1 1 1 2 1 1 3 3 1

There will always be the 1 in the first
place and the row in the second.
Create a function that returns a row from Pascal's triangle. To find the row and column you can use n!/(k!*(n-k)!) where n is the row down and k is the column.

Examples

pascals_triangle(1) ➞ "1 1"

pascals_triangle(4) ➞ "1 4 6 4 1"

pascals_triangle(6) ➞ "1 6 15 20 15 6 1"

pascals_triangle(8) ➞ "1 8 28 56 70 56 28 8 1"

In [82]:
def pascals_triangle(n):
    a = [] #an empty list
    for i in range(n+1):
        a.append([])
        a[i].append(1)
        for j in range(1, i):
            a[i].append(a[i - 1][j - 1] + a[i - 1][j])
        print(a)
        if(n != 0):
            a[i].append(1)
    return a[n]

In [84]:
pascals_triangle(4)

[[1]]
[[1, 1], [1]]
[[1, 1], [1, 1], [1, 2]]
[[1, 1], [1, 1], [1, 2, 1], [1, 3, 3]]
[[1, 1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4]]


[1, 4, 6, 4, 1]

validate_swaps(["BACDE", "EBCDA", "BCDEA", "ACBED"], "ABCDE") ➞ [True, True, False, False]

In [150]:
def validate_swaps(test, target):
    truth = []
    for i in test:
        testing = i
        test_list = list(testing)
        count = 0
        for i in range(0,len(testing)-1):
            for j in range(i+1,len(testing)):

                test_list[i],test_list[j] = test_list[j],test_list[i]
                test_list = "".join(test_list)
                if test_list == target:
                    count += 1
                test_list = list(test_list)
                test_list[j],test_list[i] = test_list[i],test_list[j]
        if count == 1:
            truth.append(True)
        elif count == 0:
            truth.append(False)
    return truth

In [151]:
validate_swaps(["BACDE", "EBCDA", "BCDEA", "ACBED"], "ABCDE")

[True, True, False, False]

In [152]:
validate_swaps(["32145", "12354", "15342", "12543"], "12345")

[True, True, True, True]

In [153]:
validate_swaps(["9786", "9788", "97865", "7689"], "9768") 

[True, False, False, False]

In [237]:
import numpy as np

arr = np.array([ [1, 0, 0], [0, 1, 0], [0, 0, 1] ])
arr2 = np.array( [ [0, 2, 2], [2, 0, 2], [2, 2, 0] ])

In [158]:
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [159]:
arr2

array([[0, 2, 2],
       [2, 0, 2],
       [2, 2, 0]])

In [179]:
for r in range(len(arr)):
    print(f"rows: {arr[r,:]}")
    print(f"columns: {arr[:,r]}")

rows: [1 0 0]
columns: [1 0 0]
rows: [0 1 0]
columns: [0 1 0]
rows: [0 0 1]
columns: [0 0 1]


In [292]:
def transform_matrix2(arr):
    arr = np.array(arr)
    answer = np.zeros([3,3])
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            answer[i][j] = sum(arr[i]) + sum(arr[:,j]) - 2*arr[i][j]
    return answer

In [294]:
def transform_matrix(arr):
    arr = np.array(arr)
    answer = np.zeros([3,3])
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if arr[i][j] == 1:
                answer[i][j] = sum(arr[i])-1 + sum(arr[:,j])-1
            elif arr[i][j] == 0:
                answer[i][j] = sum(arr[i]) + sum(arr[:,j])
    return answer

In [295]:
transform_matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

array([[0., 2., 2.],
       [2., 0., 2.],
       [2., 2., 0.]])

In [296]:
transform_matrix([ [1, 1, 1], [0, 0, 1], [0, 0, 1] ])

array([[2., 2., 4.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [297]:
transform_matrix([ [1, 1, 1], [0, 1, 1], [0, 0, 1] ]) 

array([[2., 3., 4.],
       [3., 2., 3.],
       [2., 3., 2.]])

In [299]:
transform_matrix2([ [1, 1, 1], [0, 1, 1], [0, 0, 1] ]) 

array([[2., 3., 4.],
       [3., 2., 3.],
       [2., 3., 2.]])

In [ ]:
def transform_matrix2(arr):
    arr = np.array(arr)
    answer = np.zeros([3,3])
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            answer[i][j] = sum(arr[i]) + sum(arr[:,j]) - 2*arr[i][j]
    return answer

In [322]:
#challenge 52
numbers = [i for i in range(1,7)]
dice_no = 2
target = 6
total_faces = dice_no * numbers
count = 0
repeat = []
for i in range(len(total_faces)-1):
    for j in range(i+1,len(total_faces)):
        repeat.append(set(total_faces[i],total_faces[j]))
        if total_faces[i] + total_faces[j] == target:
            
            count += 1
print(count)
    
    

TypeError: set expected at most 1 argument, got 2

In [323]:
total_faces

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]